# Generated by Django 2.2.2 on 2019-07-11 08:53

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='surveyform',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('email', models.EmailField(max_length=254)),
                ('age', models.IntegerField()),
                ('gender', models.CharField(max_length=30)),
                ('career', models.CharField(max_length=200)),
                ('change', models.CharField(max_length=10)),
                ('interest', models.CharField(max_length=100)),
                ('Qualities', models.CharField(max_length=100)),
                ('Hobbeies', models.CharField(max_length=100)),
            ],
        ),
    ]
