# Generated by Django 2.2.2 on 2019-07-16 17:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('survey', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='surveyform',
            old_name='Hobbeies',
            new_name='Hobbies',
        ),
    ]
