# Generated by Django 2.2.2 on 2019-07-10 08:49

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='sendmail',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fromemail', models.EmailField(max_length=254)),
                ('toemail', models.EmailField(max_length=254)),
                ('subject', models.CharField(max_length=20)),
                ('body', models.CharField(max_length=400)),
            ],
        ),
    ]
